all: sh

sh: sh.c                                  
	gcc $^ -o $@ -Wall                                                     

clean:                                                     
	rm -f sh  

