all: ph

ph: ph.c                                  
	gcc -g -O2 $^ -o $@ -Wall -pthread                                                     

clean:                                                     
	rm -f ph

